django-nqwrt-ecommerce/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

# dev_30
from .views import base_views, product_views, category_views ,cart_views,social_views

# dev_34
from rest_framework import routers

# dev_28
app_name = "api"

# dev_35
router = routers.DefaultRouter()
router.register(r"categories", category_views.CategoryViewSet)

# dev_9_Fruit
# GET /api/payments/ – 전체 결제 내역
# POST /api/payments/ – 결제 내역 생성
# GET /api/payments/<id>/ – 단일 결제 조회
# PUT/PATCH /api/payments/<id>/ – 수정
# DELETE /api/payments/<id>/ – 삭제
from api.views.payment_views import PaymentViewSet
router.register(r"payments", PaymentViewSet)

#dev_10_4_Fruit
from api.views.product_views import ProductViewSet
router.register('product-list', ProductViewSet, basename='product')


# dev_30
urlpatterns = [
    # base_views.py
    path("hello_world/", base_views.hello_world),
    path("hello_world_drf/", base_views.hello_world_drf),
    # product_views.py
    path("products/", product_views.products_api),
    path("product/<int:pk>/", product_views.product_api),  # dev_30
    # dev_31
    # path("categories/", category_views.CategoriesAPI.as_view()),  # dev_31
    # path("category/<int:pk>/", category_views.CategoryAPI.as_view()),  # dev_31
    # dev_33
    # path("categories/", category_views.CategoriesMixins.as_view()),  # dev_33
    # path("category/<int:pk>/", category_views.CategoryMixins.as_view()),  # dev_33
    # path("categories/", category_views.CategoriesAPI.as_view()),  # dev_34
    # path("category/<int:pk>/", category_views.CategoryAPI.as_view()),  # dev_34
    # dev_34 http://127.0.0.1:8000/api/categories/
    # 이렇게 하면 다음 경로들이 자동으로 만들어집니다:
    # GET /categories/
    # POST /categories/
    # GET /categories/<pk>/
    # PUT /categories/<pk>/
    # PATCH /categories/<pk>/
    # DELETE /categories/<pk>/
    path("", include(router.urls)),
    # dev_5_Fruit
    # djoser의 JWT 로그인 뷰를 오버라이드해서
    # 인증 설정에서 JWT 
    path("auth/", include("djoser.urls")),  # 회원가입, 비밀번호 변경 등
    path("auth/", include("djoser.urls.jwt")), # JWT 로그인/로그아웃, 토큰 갱신 등
    #dev_6_Fruit
    path("cart/", cart_views.CartAPIView.as_view(), name="api_cart"),
    path("cart/merge/", cart_views.CartMergeAPIView.as_view()),  # 👈 이렇게!
    # dev_10_Fruit
    path("dj-rest-auth/", include("dj_rest_auth.urls")),
    path("dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path("dj-rest-auth/kakao/", social_views.KakaoLoginView.as_view(), name="kakao_login"),
]

# ✅ 예시 흐름: Kakao 소셜 로그인
# 사용자가 Kakao로 로그인
# Allauth가 access_token으로 사용자 정보 요청
# populate_user() 호출 → User 객체 초기화 (필드 채움)
# User가 DB에 저장됨 (신규 가입인 경우)
# 로그인 성공 → CustomLoginSerializer.validate() 실행
# → 로그인 응답에 user 정보 포함

#http://127.0.0.1:8000/api/dj-rest-auth/login/


# ✅ 기본 엔드포인트 목록 (JWT 기준)
# HTTP Method	Endpoint URL	설명
# POST	/dj-rest-auth/login/	로그인 (JWT 또는 세션)
# POST	/dj-rest-auth/logout/	로그아웃 (세션 삭제 or 쿠키 삭제)
# POST	/dj-rest-auth/registration/	회원가입
# POST	/dj-rest-auth/password/change/	비밀번호 변경
# POST	/dj-rest-auth/password/reset/	비밀번호 초기화 이메일 전송
# POST	/dj-rest-auth/password/reset/confirm/	비밀번호 초기화 완료
# GET	/dj-rest-auth/user/	현재 로그인된 사용자 정보 가져오기
# PUT/PATCH	/dj-rest-auth/user/	사용자 정보 수정

# ✅ JWT 사용 시 추가 엔드포인트
# (dj-rest-auth 설정에서 USE_JWT = True 설정한 경우)

# HTTP Method	Endpoint URL	설명
# POST	/dj-rest-auth/token/refresh/	access token 재발급
# POST	/dj-rest-auth/token/verify/	JWT 유효성 검증

# ✅ 소셜 로그인 시 추가 엔드포인트 (예: Kakao, Google 등)
# allauth 및 dj-rest-auth.registration을 함께 설정해야 합니다.

# HTTP Method	Endpoint URL	설명
# POST	/dj-rest-auth/social/login/	소셜 로그인 (provider, access_token 전달)
# POST	/dj-rest-auth/registration/	소셜 로그인 시 회원가입

django-nqwrt-ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views

# dev_15
app_name = "cart"

urlpatterns = [
    path("", views.cart_summary, name="cart_summary"),  # dev_18
    path("add/", views.cart_add, name="cart_add"),
    path("delete/", views.cart_delete, name="cart_delete"),  # dev_19
    path("update/", views.cart_update, name="cart_update"),  # dev_19
]

django-nqwrt-ecommerce/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# dev_10_3_Fruit
from drf_spectacular.views import SpectacularJSONAPIView, SpectacularYAMLAPIView, SpectacularSwaggerView, \
    SpectacularRedocView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),  # dev_1
    path("accounts/", include("accounts.urls")),  # dev_9
    path("cart/", include("cart.urls")),  # dev_15
    path("orders/", include("orders.urls")),  # dev_24
    path("payment/", include("payment.urls")),  # dev_26
    path("api/", include("api.urls")),  # dev_28
    #dev_10_3_Fruit
    path("swagger.json/", SpectacularJSONAPIView.as_view(), name="schema-json"),
    path("swagger.yaml/", SpectacularYAMLAPIView.as_view(), name="swagger-yaml"),
    path("swagger/", SpectacularSwaggerView.as_view(url_name="schema-json"), name="swagger-ui", ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema-json"), name="redoc", ),
]

# dev_2
# http://127.0.0.1:8000/media/파일경로
# MEDIA_URL = "media/"  # ex) /media/photo1.png
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# dev_2
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-nqwrt-ecommerce/store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "store"
# dev_1
urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),  # dev_8
    path("product/<int:product_id>", views.product, name="product"),  # dev_13
    # 변수 foo 의 의미  참고:https://namu.wiki/w/foo #dev_14
    path("category/<str:foo>", views.category, name="category"),
    path("category_summary/", views.category_summary, name="category_summary"),
]

django-nqwrt-ecommerce/api/views/category_views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from rest_framework.decorators import api_view
from rest_framework.response import Response

from api.serializers.category_serializers import CategorySerializer
from store.models import Category
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet


from rest_framework.mixins import (
    ListModelMixin,
    CreateModelMixin,
    DestroyModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
)
from rest_framework.generics import GenericAPIView
from rest_framework.generics import (
    GenericAPIView,
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)

from rest_framework.exceptions import ValidationError, PermissionDenied
from rest_framework.permissions import IsAuthenticated, IsAdminUser

from rest_framework.decorators import action

# # dev_31
# class CategoriesAPI(APIView):
#     def get(self, request):
#         categories = Category.objects.all()
#         serializer = CategorySerializer(categories, many=True)
#         return Response(serializer.data)

#     def post(self, request):
#         serializer = CategorySerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)


# class CategoryAPI(APIView):
#     def get(self, request, pk):
#         category = get_object_or_404(Category, id=pk)
#         serializer = CategorySerializer(category)
#         return Response(serializer.data)

#     def put(self, request, pk):
#         category = get_object_or_404(Category, id=pk)
#         serializer = CategorySerializer(category, data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)

#     def delete(self, request, pk):
#         category = get_object_or_404(Category, id=pk)
#         category.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)


# # dev_33
# class CategoriesMixins(
#     ListModelMixin, CreateModelMixin, DestroyModelMixin, GenericAPIView
# ):
#     queryset = Category.objects.all()
#     serializer_class = CategorySerializer

#     def get(self, request, *args, **kwargs):
#         return self.list(request)

#     def post(self, request, *args, **kwargs):
#         return self.create(request)


# class CategoryMixins(
#     RetrieveModelMixin, UpdateModelMixin, DestroyModelMixin, GenericAPIView
# ):
#     queryset = Category.objects.all()
#     serializer_class = CategorySerializer

#     def get(self, request, *args, **kwargs):
#         return self.retrieve(request, *args, **kwargs)

#     def put(self, request, *args, **kwargs):
#         return self.update(request, *args, **kwargs)

#     def delete(self, request, *args, **kwargs):
#         return self.destroy(request, *args, **kwargs)


# dev_34
# class CategoriesAPI(ListCreateAPIView):
#     queryset = Category.objects.all()
#     serializer_class = CategorySerializer


# class CategoryAPI(RetrieveUpdateDestroyAPIView):
#     queryset = Category.objects.all()
#     serializer_class = CategorySerializer


# http://127.0.0.1:8000/api/categories/
class CategoriesAPI(ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    # permission_classes = [IsAuthenticated]

    # POST 요청 커스터마이징
    def create(self, request, *args, **kwargs):
        name = request.data.get("name")

        # 같은 이름의 카테고리가 이미 존재할 경우 오류
        if Category.objects.filter(name=name).exists():
            raise ValidationError(
                {"message": "이미 같은 이름의 카테고리가 존재합니다."}
            )

        response = super().create(request, *args, **kwargs)
        response.data = {
            "message": "카테고리가 성공적으로 생성되었습니다.",
            "category": response.data,
        }
        return response


# generics.RetrieveUpdateDestroyAPIView : 조회/수정/삭제
# http://127.0.0.1:8000/api/category/4/
class CategoryAPI(RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    # 조회 시 로그 찍기
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        print(f"[조회] 카테고리 ID {instance.id} - {instance.name}")
        return super().retrieve(request, *args, **kwargs)

    # 수정 시 로깅 및 응답 커스터마이징
    def update(self, request, *args, **kwargs):
        instance = self.get_object()
        print(f"[수정] 카테고리 '{instance.name}' → '{request.data.get('name')}'")
        response = super().update(request, *args, **kwargs)
        response.data = {
            "message": "카테고리가 수정되었습니다.",
            "category": response.data,
        }
        return response

    # HTTP DELETE 요청 →
    # → destroy() 실행 →
    # → perform_destroy(instance) 호출 →
    # → 객체 삭제

    # 삭제 전에 체크: 이름이 "고정"인 경우 삭제 금지
    def perform_destroy(self, instance):
        if instance.name == "고정":
            raise PermissionDenied("이 카테고리는 삭제할 수 없습니다.")
        print(f"[삭제] 카테고리 {instance.name} 삭제됨")
        instance.delete()

    # 삭제 응답 커스터마이징
    def destroy(self, request, *args, **kwargs):
        self.perform_destroy(self.get_object())
        return Response(
            {"message": "카테고리가 삭제되었습니다."}, status=status.HTTP_204_NO_CONTENT
        )


# dev_35

# ✅ ViewSet이 뭐야?
# ViewSet은 GET, POST, PUT, DELETE 같은 HTTP 메서드에 대응하는 뷰 함수들을 하나로 묶은 클래스입니다.
# 기존에 각각의 API 뷰를 ListAPIView, CreateAPIView, RetrieveAPIView 등으로 나눴다면,
# ViewSet은 이걸 한 방에 다 처리


# class CategoryViewSet(ModelViewSet):
#     queryset = Category.objects.all()
#     serializer_class = CategorySerializer


# 1.커스텀 엔드포인트 추가


# 커스터마이징     포인트	메서드
# 쿼리셋 필터링	        get_queryset()
# 시리얼라이저 변경	    get_serializer_class()
# 생성 로직 수정	    perform_create() or create()
# 삭제 제어	           perform_destroy()
# 커스텀 URL 추가	    @action(detail=True)

#dev_3_Fruit 주석처리
class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    # http://127.0.0.1:8000/api/categories/1/products/ 라는 URL로 호출
    # detail=True	/api/resource/<pk>/custom/	특정 객체에 대해 작동 (PK 필요)
    # detail=False	/api/resource/custom/	전체 또는 리스트 대상 (PK 불필요)
    # @action(detail=True, methods=["get"])
    # def products(self, request, pk=None):
    #     category = self.get_object()
    #     products = category.products.all()
    #     data = [{"name": p.name, "price": p.price} for p in products]
    #     return Response({"category": category.name, "products": data})

    # # 🎯 특정 동작을 아예 오버라이드
    # def create(self, request, *args, **kwargs):
    #     response = super().create(request, *args, **kwargs)
    #     response.data = {
    #         "message": "카테고리가 성공적으로 생성되었습니다.",
    #         "data": response.data,
    #     }
    #     return response

    # # 1. get_queryset() 커스터마이징 (권한별 필터링)
    # def get_queryset(self):
    #     user = self.request.user
    #     if user.is_staff:
    #         return Category.objects.filter(id=1)
    #     return Category.objects.all()

django-nqwrt-ecommerce/api/views/product_views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from store.models import Product
from api.serializers.product_serializers import ProductSerializer
# dev_10_4_Fruit
from rest_framework.decorators import action
from django.db.models import Max

# Create your views here.

# dev_10_3_Fruit
from drf_spectacular.utils import extend_schema,OpenApiParameter
# 함수형 뷰
@extend_schema(
    methods=['GET'], # 이 데코레이터를 적용할 HTTP 메서드
    summary='상품들을 조회', # API 요약 설명
    description='상품의 리스트를 조회하는 API입니다.', # API 상세 설명
    responses={200: ProductSerializer(many=True)}, # 응답 스키마
)
@extend_schema(
    methods=['POST'], # 이 데코레이터를 적용할 HTTP 메서드
    summary='상품을 생성', # API 요약 설명
    description='상품을 생성하는 API입니다.', # API 상세 설명
    request=ProductSerializer,
    responses={200: ProductSerializer(many=False)}, # 응답 스키마
)
# dev_29 추가 되도록
@api_view(["GET", "POST"])
def products_api(request):

    if request.method == "GET":
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

    # 디시리얼라이져
    if request.method == "POST":
        serializer = ProductSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)


@api_view(["GET", "PUT", "DELETE"])
def product_api(request, pk):
    product = get_object_or_404(Product, id=pk)

    if request.method == "GET":
        serializer = ProductSerializer(product)
        return Response(serializer.data)

    elif request.method == "PUT":
        serializer = ProductSerializer(product, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    elif request.method == "DELETE":
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

from rest_framework import viewsets, filters
from rest_framework.pagination import PageNumberPagination
from django_filters.rest_framework import DjangoFilterBackend

#dev_10_4_Fruit
# 페이지네이션 클래스 (옵션)
# ✅ 요청 예시
# /api/product-list/?page=2	페이지 2
# /api/product-list/?search=포도	'포도' 포함 검색
# /api/product-list/?category=4	카테고리 ID가 4번인 상품 필터링
# /api/product-list/?ordering=price	가격 오름차순 정렬
# /api/product-list/?ordering=-id	최신순 정렬

# filters.py
import django_filters

#GET /api/product-list/?min_price=100&max_price=300
class ProductFilter(django_filters.FilterSet):
    min_price = django_filters.NumberFilter(field_name='price', lookup_expr='gte')
    max_price = django_filters.NumberFilter(field_name='price', lookup_expr='lte')

    class Meta:
        model = Product
        fields = ['category', 'min_price', 'max_price']

class ProductPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 100

# 읽기 전용 ViewSet 
# POST 추가 가능 필요시
# ModelViewSet
class ProductViewSet(viewsets.ReadOnlyModelViewSet):  
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    pagination_class = ProductPagination
    
    #  추가
    filterset_class = ProductFilter  # 필터셋 클래스 지정

    # 필터링/검색/정렬 backends 설정
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    
    # 필터링 항목 (URL에서 ?category=값 으로 필터링 가능)
    filterset_fields = ['category']

    # 검색 필드 (?search=아이폰)
    search_fields = ['name', 'description']  # 필요에 따라 수정 가능

    # 정렬 필드 (?ordering=price 또는 ?ordering=-created)
    ordering_fields = ['id','price', 'name']
    ordering = ['id']  # 기본 정렬
    

    #ViewSet 에서 URL 추가
    @action(detail=False, methods=['get'], url_path='max-price')
    def max_price(self, request):
        max_price = Product.objects.aggregate(Max('price'))['price__max'] or 0
        return Response({'max_price': max_price})

django-nqwrt-ecommerce/templates/store/category.html
<!--dev_13-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
  {% include "layout/head.html" %}
{% endblock head %}
{% block navi %}
  <div class="d-flex flex-column vh-100 justify-content-between">
    {% include "layout/navbar.html" %}
  {% endblock navi %}
  {% block header %}
    <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">{{ category }}</h1>
          <p class="lead fw-normal text-white-50 mb-0">Category Page</p>
        </div>
      </div>
    </header>
  {% endblock header %}
  <!--템플릿 적용-->
  {% block content %}
    <section class="py-5">
      <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          {% for product in products %}
            <div class="col mb-5">
              <div class="card h-100">
                {% if product.is_sale %}
                  <!-- Sale badge-->
                  <div class="badge bg-dark text-white position-absolute"
                       style="top: 0.5rem;
                              right: 0.5rem">Sale</div>
                {% endif %}
                <!-- Product image-->
                <img class="card-img-top"
                     style="object-fit:fill"
                     src="{{ product.image.url }}"
                     alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                  <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ product.name }}</h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    {% if product.is_sale %}<span class="text-muted text-decoration-line-through">$20.00</span>{% endif %}
                    ${{ product.price }}
                  </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center">
                    <a class="btn btn-outline-dark mt-auto"
                       href="{% url 'store:product' product.id %}">View Product</a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  {% endblock content %}
  {% block footer %}
    {% include "layout/footer.html" %}
  {% endblock footer %}
</div>

django-nqwrt-ecommerce/templates/store/category_summary.html
<!--dev_13-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
  {% include "layout/head.html" %}
{% endblock head %}
{% block navi %}
  <div class="d-flex flex-column vh-100 justify-content-between">
    {% include "layout/navbar.html" %}
  {% endblock navi %}
  {% block header %}
    <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">카테고리</h1>
          <p class="lead fw-normal text-white-50 mb-0">Choose your Category Below..</p>
        </div>
      </div>
    </header>
  {% endblock header %}
  <!--템플릿 적용-->
  {% block content %}
    <div class="container">
      <div class="row">
        <center>
          <div class="col-8">
            <br />
            <br />
            {% for category in categories %}
              <h3>
                <a href="{% url 'store:category' category %}">{{ category }}</a>
              </h3>
            {% endfor %}
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
          </div>
        </center>
      </div>
    </div>
  {% endblock content %}
  {% block footer %}
    {% include "layout/footer.html" %}
  {% endblock footer %}
</div>

django-nqwrt-ecommerce/templates/store/product.html
<!--dev_13-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
  {% include "layout/head.html" %}
{% endblock head %}
{% block navi %}
  <div class="d-flex flex-column vh-100 justify-content-between">
    {% include "layout/navbar.html" %}
  {% endblock navi %}
  <!--템플릿 적용-->
  {% block content %}
    <section class="py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
          <div class="col-md-6">
            <img class="card-img-top mb-5 mb-md-0"
                 src="{{ product.image.url }}"
                 alt="...">
          </div>
          <div class="col-md-6">
            <div class="small mb-1">SKU: BST-498</div>
            <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
            <div class="fs-5 mb-5">
              {% if product.is_sale %}
                <span class="text-decoration-line-through">{{ product.price }}원</span>
                <span>{{ product.price }}원</span>
              {% else %}
                {{ product.price }}원
              {% endif %}
            </div>
            <p class="lead">{{ product.description }}</p>
            <div class="d-flex">
              <input class="form-control text-center me-3"
                     id="inputQuantity"
                     type="num"
                     value="1"
                     style="max-width: 3rem">
              <button class="btn btn-outline-dark flex-shrink-0"
                      type="button"
                      value="{{ product.id }}"
                      id="add-cart">
                <!--dev_15-->
                <i class="bi-cart-fill me-1"></i>
                <!--dev_15-->
                Add to cart(장바구니 담기)
              </button>
            </div>
            <br>
            <a class="btn btn-secondary" href="{% url 'store:home' %}">홈으로</a>
          </div>
        </div>
      </div>
    </section>
  {% endblock content %}
  {% block footer %}
    {% include "layout/footer.html" %}
  {% endblock footer %}
</div>
<!--dev_15-->
{% block script %}
  <script>
  $(document).on('click', '#add-cart',function(e){
  $.ajax({
    type:"POST",
    url:"{% url 'cart:cart_add' %}",
    data:{
      product_id: $('#add-cart').val(),
      //product_qty: $('#qty-cart option:selected').text(),
      product_qty: $('#inputQuantity').val(),
      csrfmiddlewaretoken:'{{  csrf_token }}',
      action: 'post'
    },
    success : function(json){
      console.log(json)
      //dev_16
      $('#cart_quantity').text(json.qty) 
    },
    error : function(e){
      console.log(e)
    }
  })
});
  </script>
{% endblock script %}